apiVersion: v1
kind: Service
metadata:
  name: thecosmicinitiative
  labels:
    {{- include "docs.labels" . | nindent 4 }}
    app: "thecosmicinitiative.io"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "docs.selectorLabels" . | nindent 4 }}
    app: "thecosmicinitiative.io"
